Patch relnotes.k8s.io to release v1.27.0-alpha.3
kubernetes-sigs/release-notes pull request #474
Opened 2023-03-03 14:54 UTC by rjsadow

Automated patch to update relnotes.k8s.io to k/k version `v1.27.0-alpha.3`

2023-03-04 13:48 UTC, harshanarayana requested changes

2023-03-04 13:48 UTC, harshanarayana commented on src/assets/release-notes-1.27.0-alpha.3.json
> +    "text": "```\n\n#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:\n\n\u003c!--\nThis section can be blank if this pull request does not require a rele
Some of these PRs have no Release notes attached to them. We can cleanup the text/markdown bits for those and make them `None`

2023-03-04 13:48 UTC, harshanarayana commented on src/assets/release-notes-1.27.0-alpha.3.json
> +    "markdown": "```\n  \n  #### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:\n  \n  \u003c!--\n  This section can be blank if this pull request does not
```suggestion
    "markdown": "NONE ([#115758](https://github.com/kubernetes/kubernetes/pull/115758), [@sourcelliu](https://github.com/sourcelliu)) [SIG API Machinery]",
```

2023-03-04 13:49 UTC, harshanarayana commented on src/assets/release-notes-1.27.0-alpha.3.json
> +    "markdown": "```\n  \n  #### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:\n  \n  \u003c!--\n  This section can be blank if this pull request does not
Leaving behind a few minor comments for this cleanup. There are two more items that need the same processing on this file. Please take a look

2023-03-08 02:01 UTC, harshanarayana commented
/lgtm
/approve
/assign cpanato

2023-03-08 08:24 UTC, saschagrunert approved these changes

2023-03-08 08:25 UTC, merged